@startuml
skinparam roundcorner 5
skinparam linetype ortho

entity Rol {
    * id_rol : INT (PK)
    --
    * nombre_rol : VARCHAR(30)
}


entity Usuario {
    * id_usuario : INT (PK)
    --
    * nombre_completo : VARCHAR(100)
    * username: VARCHAR(30)
    * contraseña : VARCHAR(255)
    * id_rol : INT (FK)
}

entity Preferencias_Usuario {
    * id_usuario : INT (PK)
    --
    * nivel_elegido : VARCHAR(20) 'Ninguno, Basico, Intermedio, '
    * objetivo_diario: INT
    * modo_audio: VARCHAR(20) 'Audio, Sin_voces, Muteado'
    * ui_simple: BOOLEAN
}

entity Stats_Usuario {
    * id_usuario : INT (FK)
    --
    * nivel_actual : VARCHAR(2) 'A1, A2, B1, B2, C1, C2'
    * vidas_actuales : INT
    * puntos_totales : INT
    * racha_actual : INT
    * vidas_maximas: INT
    * fecha_ultima_actividad: DATETIME
    * ui_simple: BOOLEAN
}


entity Progreso_Leccion {
    * id_cuenta : INT (PK, FK)
    * id_leccion : INT (PK, FK)
    --
    * completado : BOOLEAN
    * fecha_completado : DATETIME
}

entity Seccion {
    * id_seccion : INT (PK)
    --
    * id_nivel : INT (FK)
    * title : VARCHAR(128)
    * position : INT
}

entity Unidad {
    * id_unidad : INT (PK)
    --
    * id_seccion : INT (FK)
    * about : VARCHAR(128)
    * position : INT
}

entity Grupo_Lecciones {
    * id_grupo_lecciones : INT (PK)
    --
    * id_unidad : INT (FK)
    * position : INT 
    * title : VARCHAR(128)
}

entity Leccion {
    * id_leccion : INT (PK)
    --
    * id_grupo_lecciones : INT (FK)
    * id_tipo_de_leccion : INT (FK)
    * contenido_didactico : TEXT ' Datos de trivias o preguntas del examen
    * experiencia_otorgada : INT
    * es_examen_ubicacion : BOOLEAN ' TRUE si la lección pertenece al test inicial
    religion_restriccion : VARCHAR(100) ' NULL si es para todos, o específica (ej: "Catolicismo")
}

entity Tipo_de_Leccion {
    * id_tipo_de_leccion : INT (PK)
    --
    * name : VARCHAR(128) ' Cámara, Trivia, Imitación, Examen Ubicación
}

entity Seña {
    * id_seña : INT (PK)
    --
    * id_recurso : INT (FK)
    * id_categoria : INT (FK)
    * significado : VARCHAR(128)
}

entity Categoria {
    * id_categoria : INT (PK)
    --
    * nombre_categoria : VARCHAR(128) ' Matemáticas, Historia, Psicología, Religión...
}

entity Recurso {
    * id_recurso : INT (PK)
    --
    * tipo_de_recurso : VARCHAR(100) 'Video, Animacion_2D, Animacion_3D, Estatico'
    * contenido_recurso : BOB
}

' --- RELACIONES CORREGIDAS (Muchos a la izquierda, Uno a la derecha) ---

' Núcleo e Historial
Usuario ||..|| Cuenta
Progreso_Leccion }|..|| Cuenta
Progreso_Leccion }|..|| Leccion
Cuenta }|..|| Nivel

' Estructura Educativa Escalar
Seccion }|..|| Nivel
Unidad }|..|| Seccion
Grupo_Lecciones }|..|| Unidad
Leccion }|..|| Grupo_Lecciones
Leccion }|..|| Tipo_de_Leccion

' Diccionario de Señas, Recursos Multimedia y Categorías
Seña }|..|| Categoria_Seña
Seña }|..|| Recurso
Recurso }|..|| Tipo_de_Recursos

@enduml